Added appropriate action/reaction images from user suggestion.
veldlabs/miki-bot pull request #430
Opened 2018-05-03 12:21 UTC by adv0catus

https://feathub.com/Mikibot/Miki/+16

2018-05-15 15:53 UTC, velddev commented
No idea what this does. I see a lot of already duplicates.

2018-05-17 07:42 UTC, velddev commented
@adv0catus if you have the time, remove the duplicate gifs, and then I'll merge it.

2018-05-17 10:04 UTC, adv0catus commented
@velddev This weekend. How do you feel about comments being added beside each imgur link quickly describing it with the intention of reducing/eliminating duplicates?

2018-05-17 10:54 UTC, velddev requested changes

2018-05-17 10:54 UTC, velddev commented on Miki/Modules/ActionsModule.cs
> +		"http://i.imgur.com/Qv5CAqB.gif",
Duplicate

2018-05-17 10:54 UTC, velddev commented on Miki/Modules/ActionsModule.cs
> +		"http://i.imgur.com/B49G7oQ.gif",
Duplicate

2018-05-17 10:54 UTC, velddev commented on Miki/Modules/ActionsModule.cs
> +		"http://i.imgur.com/w6cGU77.gif",
Duplicate

2018-05-17 10:54 UTC, velddev commented on Miki/Modules/ActionsModule.cs
> +		"https://i.imgur.com/fIgeJUr.gif"
Duplicate

2018-05-17 10:54 UTC, velddev commented on Miki/Modules/ActionsModule.cs
> +		"http://i.imgur.com/PaKqsBx.gif",
Duplicate

2018-05-17 10:54 UTC, velddev commented on Miki/Modules/ActionsModule.cs
> +		"http://i.imgur.com/ta1u312.gif"
Duplicate

2018-05-17 10:54 UTC, velddev commented on Miki/Modules/ActionsModule.cs
> +		"http://i.imgur.com/eYf50FP.gif"
Odd aspect ration

2018-05-17 10:54 UTC, velddev commented on Miki/Modules/ActionsModule.cs
> +		"http://i.imgur.com/XGpq4S7.gif",
Duplicate

2018-05-17 10:54 UTC, velddev commented on Miki/Modules/ActionsModule.cs
> +		"http://i.imgur.com/uvXG6uU.gif"
Duplicate

2018-05-17 10:54 UTC, velddev commented on Miki/Modules/ReactionsModule.cs
> +				"http://i.imgur.com/u1wxWx9.gif"
Odd aspect ratio

2018-05-19 15:48 UTC, closed without merging